
clean:
	rm -f c
	rm -f fort.11
	rm -f h_fcn_ts
	rm -f h_fcn_ts_cart
	rm -f mndo.in
	rm -f mndo.out
	rm -f newopt.h_vis
	rm -f no.f_restart
	rm -f no.gdiis_g_restart
	rm -f no.gdiis_x_restart
	rm -f no.g_restart
	rm -f no.gtmp_restart
	rm -f no.h
	rm -f no.h_restart
	rm -f no.x_restart
	rm -f z
	rm -f copt.c_start
	rm -f copt.c_vis
	rm -f copt.result
	rm -f zopt.result
	rm -f zopt.z_start
	rm -f zopt.z_vis

zopt_test:
	cp zopt.z_vis.keep zopt.z_vis
	cp zopt.hessian newopt.h_vis

copt_test:
	cp copt.c_vis.keep copt.c_vis
	cp copt.hessian newopt.h_vis
