charmm_map = {}

charmm_map['N'] = 'N'
charmm_map['NE'] = 'N'
charmm_map['ND1'] = 'N'
charmm_map['ND2'] = 'N'
charmm_map['NH1'] = 'N'
charmm_map['NH2'] = 'N'
charmm_map['NE'] = 'N'
charmm_map['NE1'] = 'N'
charmm_map['NE2'] = 'N'
charmm_map['NZ'] = 'N'

charmm_map['O'] = 'O'
charmm_map['O1'] = 'O'
charmm_map['O2'] = 'O'
charmm_map['O3'] = 'O'
charmm_map['O4'] = 'O'
charmm_map['O5'] = 'O'
charmm_map['O6'] = 'O'
charmm_map['OD1'] = 'O'
charmm_map['OD2'] = 'O'
charmm_map['OG'] = 'O'
charmm_map['OG1'] = 'O'
charmm_map['OE'] = 'O'
charmm_map['OE1'] = 'O'
charmm_map['OE2'] = 'O'
charmm_map['OH'] = 'O'
charmm_map['OH1'] = 'O'
charmm_map['OH2'] = 'O'

charmm_map['OCT1'] = 'O'        
charmm_map['OCT2'] = 'O'        
charmm_map['OT1'] = 'O'        
charmm_map['OT2'] = 'O'        

charmm_map['C'] = 'C'
charmm_map['C1'] = 'C'
charmm_map['C2'] = 'C'
charmm_map['C3'] = 'C'
charmm_map['CA'] = 'C'
charmm_map['CB'] = 'C'
charmm_map['CD'] = 'C' 
charmm_map['CD'] = 'C' 
charmm_map['CD1'] = 'C' 
charmm_map['CD2'] = 'C' 

charmm_map['CE'] = 'C' 
charmm_map['CE1'] = 'C' 
charmm_map['CE2'] = 'C' 
charmm_map['CE3'] = 'C' 

charmm_map['CG'] = 'C'
charmm_map['CG1'] = 'C'
charmm_map['CG2'] = 'C'

charmm_map['CH'] = 'C'
charmm_map['CH1'] = 'C'
charmm_map['CH2'] = 'C'

charmm_map['CZ'] = 'C'
charmm_map['CZ1'] = 'C'
charmm_map['CZ2'] = 'C'
charmm_map['CZ3'] = 'C'

charmm_map['H'] = 'H'

charmm_map['H1'] = 'H'
charmm_map['H2'] = 'H'
charmm_map['H3'] = 'H'
charmm_map['H4'] = 'H'
charmm_map['H5'] = 'H'
charmm_map['HA'] = 'H'
charmm_map['HA1'] = 'H'
charmm_map['HA2'] = 'H'
charmm_map['HB'] = 'H'
charmm_map['HB1'] = 'H'
charmm_map['HB2'] = 'H'
charmm_map['HB3'] = 'H'
charmm_map['HD1'] = 'H'
charmm_map['HD11'] = 'H'
charmm_map['HD2'] = 'H'
charmm_map['HD3'] = 'H'
charmm_map['HD12'] = 'H'
charmm_map['HD13'] = 'H'
charmm_map['HD21'] = 'H'
charmm_map['HD22'] = 'H'
charmm_map['HD23'] = 'H'

charmm_map['HE'] = 'H'
charmm_map['HE1'] = 'H'
charmm_map['HE2'] = 'H'
charmm_map['HE3'] = 'H'
charmm_map['HE21'] = 'H'
charmm_map['HE22'] = 'H'

charmm_map['HG'] = 'H'
charmm_map['HG1'] = 'H'
charmm_map['HG2'] = 'H'
charmm_map['HG3'] = 'H'

charmm_map['HG11'] = 'H'
charmm_map['HG12'] = 'H'
charmm_map['HG13'] = 'H'
charmm_map['HG21'] = 'H'
charmm_map['HG22'] = 'H'
charmm_map['HG23'] = 'H'

charmm_map['HH'] = 'H'
charmm_map['HH1'] = 'H'
charmm_map['HH2'] = 'H'

charmm_map['HG'] = 'H'

charmm_map['HO1'] = 'H'
charmm_map['HO2'] = 'H'
charmm_map['HO3'] = 'H'
charmm_map['HO4'] = 'H'
charmm_map['HO5'] = 'H'
charmm_map['HO6'] = 'H'

charmm_map['HZ'] = 'H'
charmm_map['HZ1'] = 'H'
charmm_map['HZ2'] = 'H'
charmm_map['HZ3'] = 'H'

charmm_map['HT1'] = 'H'
charmm_map['HT2'] = 'H'
charmm_map['HT3'] = 'H'

charmm_map['HH11'] = 'H'
charmm_map['HH12'] = 'H'
charmm_map['HH21'] = 'H'
charmm_map['HH22'] = 'H'

charmm_map['HN'] = 'H'

charmm_map['P'] = 'P'
charmm_map['SG'] = 'S'
charmm_map['SD'] = 'S'
charmm_map['ZN'] = 'ZN'
charmm_map['CU'] = 'CU'

